openapi: 3.0.0
info:
  title: LoopBack Application
  version: 1.0.0
servers: 
- url: https://api.openweathermap.org/data/2.5/
paths:
  /onecall/:
    get:
      tags:
      - getForecast
      description: 'One call'
      operationId: getForecast
      summary: List api.openweathermap.org 2.5s
      parameters:
        - description: apiKey
          in: query
          name: apiKey
          schema:
            type: string
        - description: latitude
          in: query
          name: lat
          schema:
            type: string
        - description: longitude
          in: query
          name: lon
          schema:
            type: string
        - description: units
          in: query
          name: units
          schema:
            type: string
        - description: exclude
          in: query
          name: exclude
          schema:
            type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    Response:
      type: object
      required:
      - lat
      - lon
      properties:
        lat: 
          type: number
        lon: 
          type: number
        timezone: 
          type: string
        timezone_offset: 
          type: integer
          format: int32
        current:
          $ref: '#/components/schemas/CurrentInfo'
        minutely: 
          type: array
          items: 
            $ref: '#/components/schemas/MinutelyInfo'
        hourly: 
          type: array
          items: 
            $ref: '#/components/schemas/HourlyInfo'
        daily: 
          type: array
          items: 
            $ref: '#/components/schemas/DailyInfo'
        alerts: 
          type: array
          items:
            $ref: '#/components/schemas/Alerts'
    CurrentInfo: 
      type: object
      properties: 
        dt: 
          type: integer
          format: int32
        sunrise: 
          type: integer
          format: int32
        sunset: 
          type: integer
          format: int32
        temp: 
          type: number
        feels_like: 
          type: number
        pressure: 
          type: integer
          format: int32
        humidity: 
          type: integer
          format: int32
        dew_point: 
          type: number
        uvi: 
          type: number
        clouds: 
          type: integer
          format: int32
        visibility: 
          type: integer
          format: int32
        wind_speed: 
          type: number
        wind_deg: 
          type: integer
          format: int32
        wind_gust: 
          type: number
        weather: 
          type: array
          items:
            $ref: '#/components/schemas/CurrentWeatherItem'
    CurrentWeatherItem:
      type: object
      properties: 
        id: 
          type: integer
          format: int32
        main: 
          type: string
        description: 
          type: string
        icon: 
          type: string
    MinutelyInfo:
      type: object
      properties: 
        dt: 
          type: integer
          format: int32
        precipitation: 
          type: integer
          format: int32
    HourlyInfo:
      type: object
      properties: 
        dt: 
          type: integer
          format: int32
        temp: 
          type: number
        feels_like: 
          type: number
        pressure: 
          type: integer
          format: int32
        humidity: 
          type: integer
          format: int32
        dew_point: 
          type: integer
          format: int32
        uvi: 
          type: number
        clouds: 
          type: integer
          format: int32
        visibility: 
          type: integer
          format: int32
        wind_speed: 
          type: number
        wind_deg: 
          type: integer
          format: int32
        wind_gust: 
          type: number
        weather: 
          type: array
          items:
            $ref: '#/components/schemas/HourlyWeatherItem'
        pop: 
          type: integer
          format: int32
    HourlyWeatherItem:
      type: object
      properties: 
        id: 
          type: integer
          format: int32
        main: 
          type: string
        description: 
          type: string
        icon: 
          type: string
    DailyInfo:
      type: object
      properties: 
        dt: 
          type: integer
          format: int32
        sunrise: 
          type: integer
          format: int32
        sunset: 
          type: integer
          format: int32
        moonrise: 
          type: integer
          format: int32
        moonset: 
          type: integer
          format: int32
        moon_phase: 
          type: number
        temp: 
          $ref: '#/components/schemas/DailyTempInfo'
        feels_like: 
          $ref: '#/components/schemas/DailyFeelsLikeInfo'
        pressure: 
          type: integer
          format: int32
        humidity: 
          type: integer
          format: int32
        dew_point: 
          type: number
        wind_speed: 
          type: number
        wind_deg: 
          type: integer
          format: int32
        wind_gust: 
          type: number
        weather: 
          type: array
          items: 
            $ref: '#/components/schemas/DailyWeatherItem'
        clouds: 
          type: integer
          format: int32
        pop: 
          type: number
        uvi: 
          type: number
    DailyTempInfo:
      type: object
      properties: 
        day: 
          type: number
        min: 
          type: number
        max: 
          type: number
        night: 
          type: number
        eve: 
          type: number
        morn: 
          type: number
    DailyFeelsLikeInfo:
      type: object
      properties: 
        day: 
          type: number
        night: 
          type: number
        eve: 
          type: number
        morn: 
          type: number
    DailyWeatherItem:
      type: object
      properties: 
        id: 
          type: integer
          format: int32
        main: 
          type: string
        description: 
          type: string
        icon: 
          type: string
    Alerts: 
      type: object
      properties: 
        sender_name: 
          type: string
        event: 
          type: string
        start: 
          type: integer
          format: int32
        end: 
          type: integer
          format: int32
        description: 
          type: string
        tags: 
          type: array
          items: 
            type: string
    ErrorModel:
      required:
      - cod
      - message
      type: object
      properties:
        message:
          type: string
        code:
          maximum: 600
          minimum: 100
          type: integer